<!DOCTYPE html>
<html lang="fr">
<html>

<head>
<meta charset='utf-8' />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="keywords" content="Sat@,Sata Contact,sata-system,sata-alarme,alarme">
<link href='../resources/css/main.css' rel='stylesheet' />
<link href='../resources/css/agenda.css' rel='stylesheet' />
<link href='../resources/css/RDV.css' rel='stylesheet' />

<title>Agenda SATA</title>
</head>

<body>

  <div id='calendar'></div>
  

<div class="flex">
<div>
    <button onclick="openNav2()" class="button">Vous souhaitez prendre un rendez-vous ?</button>
</div>
<div>
    <a href="../controllers/home.php"><button class="button2">Retour à l'accueil</button></a>
</div>
</div>

<div id="mySidebar2" class="sidebar">
<a href="javascript:void(0)" class="closebtn" onclick="closeNav2()">&times;</a>
<formul3 class="form-style-3">
    <h1>Prendre un rendez-vous</h1>
    <h3>(vous devez être connecté)</h3>
      <form action="../controllers/RDV.php" method="POST">
          <div class="section"><span>1</span>Jour</div>
          <div class="inner-wrap">
              <label><input type="date" name="date" required></label>
          </div>
          <div class="section"><span>2</span>Heure de début</div>
              <div class="inner-wrap">
              <label><input type="time" name="start" required/></label>
          </div>

          <div class="section"><span>3</span>Motif du rdv</div>
          <div class="inner-wrap">   
            <select name="title" required>
                <option value="">--Choisissez un motif--</option>
                <option value="Depannage">Dépannage informatique</option>
                <option value="Pose">Pose d'alarme</option>
                <option value="Autre">Autre</option>
            </select>
          </div>

          <div class="section"><span>4</span>Commentaire (facultatif)</div>
              <div class="inner-wrap">
              <textarea input type="comment" name="comment"></textarea>
          </div>
          <div class="button-section3">
          <input type="submit" name="RDV" />
          </div>
      </form>
  </formul3>
</div>


<script src='../resources/js/script.js'></script>
<script src='../resources/js/main.js'></script>
<script src='../resources/js/locales-all.js'></script>
<script src='../resources/js/agenda.js'></script>
</body>
</html>
