<?php require '../views/header.phtml'; ?>

<sectionCGU>
  <h1>Conditions générales d'utilisation</h1>
  <div class="trait">
    <hr />
  </div>
  <p class="gras">
    Merci de lire ces conditions attentivement avant d'utiliser les services de
    ce site.
    <br/>Nous proposons un service de vente sur Internet plus spécifiquement
    destiné aux particuliers.
    <br />L'accès au site, sa consultation et son utilisation sont subordonnés à
    l'acceptation sans réserve des présentes Conditions Générales d'Utilisation.
  </p>
  <div class="trait">
    <hr />
  </div>
  <br/>
  <p>
  La société SATA au capital de (A RENSEIGNER), est immatriculée au
    registre du commerce et des sociétés sous le numéro (A RENSEIGNER).
    <br />Siège social : 24 rue de Lorraine, 54300 LUNEVILLE
    <br />Le Directeur de la société est Dominique CONSTANTIN
    <br />Numéro de TVA intracommunautaire : A RENSEIGNER
    <br />Pour toute question sur l'entreprise, vous pouvez
    <a href="#">nous envoyer vos questions par email.</a>
    <br /><br />CONDITIONS GENERALES D'UTILISATION DU SITE (A RENSEIGNER) (DATE
    A RENSEIGNER)
  </p>
  <br /><br />
  <div class="trait">
    <hr />
  </div>
  <br />
  <h2>DEFINITIONS</h2>
  <p>
    Achat Direct : permet à l’acheteur d’acheter le bien au prix indiqué dans
    l’annonce en cliquant sur “Acheter” depuis l’annonce et ainsi d’accepter
    directement l’offre du site.
    <br /><br />Acheteur : désigne tout utilisateur personne physique majeure
    titulaire d’un Compte personnel qui achète ou souhaite acheter un ou
    plusieurs biens sur le Site.
    <br /><br />Annonce : désigne l'ensemble des éléments et données (visuelles,
    textuelles, photographies), déposé sur le site, en vue de vendre un bien
    diffusé sur le Site.
    <br /><br />Bien : désigne tout produit dont la vente n’est pas interdite
    par la réglementation française applicable et qui est proposé à la vente sur
    le Site via nos services de paiement.
    <br /><br />Bordereau d’affranchissement : désigne l’affranchissement en
    Lettre avec Suivi ou en Colissimo ou en Mondial Relay, portant l’adresse
    renseignée par l’acheteur lors de l’achat direct. Ce bordereau doit être
    collé sur le colis par le responsable des ventes.
    <br /><br />Colis : désigne le paquet précautionneusement emballé par le
    responsable des ventes, conformément aux conditions d’admission des colis de
    Mondial Relay ou les règles et conseils de Colissimo, sur lequel est collé
    le bon d’envoi pour le Service de Livraison Mondial Relay ou le Bordereau
    d’affranchissement pour le Service de Livraison Colissimo et contenant le ou
    les Biens achetés par l’acheteur via nos services de paiement, destiné à
    être envoyé via le Service de Livraison.
    <br /><br />Compte Personnel : désigne l'espace gratuit, accessible depuis
    notre site Internet, que tout Particulier doit se créer, et à partir duquel
    il peut procéder à des achats.
    <br /><br />Frais de Livraison : désigne selon le service de livraison
    sélectionné les frais d’expédition fixés par notre société sur la base des
    tarifs Mondial Relay ou les tarifs universels de La Poste.
    <br /><br />Messagerie : désigne le système de formulaire de contact mis à
    la disposition des utilisateurs, leur permettant la communication avec notre
    société. La messagerie est uniquement accessible aux utilisateurs disposant
    d'un compte personnel.
    <br /><br />Service de Livraison :
  </p>
  <ul class="liste">
    <li>
      Le service de livraison Mondial Relay désigne le service de transport et
      de livraison, depuis et à destination de la France métropolitaine, à la
      charge de l’acheteur, permettant au vendeur d’envoyer le bien vendu dans
      le cadre d’une transaction via nos services de paiement et dont le
      transport n’est pas interdit par Mondial Relay.
    </li>
    <li>
      Le Service de livraison Colissimo désigne le service d’envoi disponible
      dans le cadre de l’achat direct, de transport et de livraison, depuis et à
      destination de la France métropolitaine, proposé par Colissimo (La Poste),
      à la charge de l’acheteur, permettant au vendeur d’envoyer le bien vendu
      dans le cadre d’une transaction via nos services de paiement et dont le
      transport n’est pas interdit par La Poste.
    </li>
  </ul>
  <p>
    <br />Site : désigne le site internet exploité par notre société, accessible
    principalement depuis l'URL www.(A RENSEIGNER) et permettant aux
    utilisateurs d'accéder via internet à nos services.
    <br /><br />Utilisateur : désigne tout visiteur, ayant accès à nos services
    via le site et consultant nos services, accessible depuis les différents
    supports.
    <br /><br />Transaction : désigne les transactions qui transfèrent la
    propriété d’un bien d’un vendeur à un acheteur, à compter de la validation
    du paiement et la réception du bien par l’acheteur, en vertu du contrat de
    vente conclu entre eux via l’utilisation d'un service de paiement.
  </p>
  <br/> <br/>
  <div class="trait">
    <hr />
  </div>
  <h2>ACCEPTATION</h2>
  <p>
    Les CGU ont pour objet de déterminer les conditions d'utilisation des
    services mis à disposition des utilisateurs via notre site.
    <br />Tout utilisateur/vendeur déclare en accédant et utilisant nos
    services, depuis le site, avoir pris connaissance des présentes Conditions
    Générales d’Utilisation et les accepter expressément sans réserve et/ou
    modification de quelque nature que ce soit. Les présentes CGU sont donc
    pleinement opposables aux utilisateurs/vendeurs.
  </p>
  <br/><br/><br />
  <div class="trait">
    <hr />
  </div>
  <h2>Utilisation des données de notre site</h2>
  <p>
    Tout Utilisateur déclare être informé qu’il devra, pour accéder à nos
    services, disposer d’un accès à Internet souscrit auprès du fournisseur de
    son choix, dont le coût est à sa charge, et reconnaît que :
  </p>
  <ul class="liste">
    <li>
      La fiabilité des transmissions est aléatoire en raison, notamment, du
      caractère hétérogène des infrastructures et réseaux sur lesquelles elles
      circulent et que, en particulier, des pannes ou saturations peuvent
      intervenir ;
    </li>
    <li>
      Il appartient à l’utilisateur de prendre toute mesure qu’il jugera
      appropriée pour assurer la sécurité de son équipement et de ses propres
      données, logiciels ou autres, notamment contre la contamination par tout
      virus et/ou de tentative d’intrusion dont il pourrait être victime ;
    </li>
    <li>
      Tout équipement connecté à notre site est et reste sous l’entière
      responsabilité de utilisateur, la responsabilité de notre société ne
      pourra pas être recherchée pour tout dommage direct ou indirect qui
      pourrait subvenir du fait de leur connexion au site Internet.
    </li>
  </ul>
  <div class="trait">
    <hr />
  </div>
  <h2>Règles générales</h2>
  <p>
    Tout utilisateur s’engage, le cas échéant, à respecter et à maintenir la
    confidentialité des Identifiants de connexion à son Compte Personnel et
    reconnaît expressément que toute connexion à son Compte Personnel, ainsi que
    toute transmission de données depuis son Compte Personnel sera réputée avoir
    été effectuée par l’utilisateur.
    <br />Toute perte, détournement ou utilisation des Identifiants de connexion
    et leurs éventuelles conséquences relèvent de la seule et entière
    responsabilité de l'utilisateur.
  </p>
  <h2>Fonctionnalités</h2>
  <p>
    Notre Service proposé aux utilisateurs varie en fonction de la qualité de
    "utilisateur non enregistré" ou de "utilisateur enregistré"
  </p>
  <br /><br /><br />
  <h3>
    Fonctionnalités accessibles aux Utilisateurs non enregistrés depuis le site
  </h3>
  <p>
La consultation de toutes les Annonces diffusées
    <br />La mise en contact avec la société
    <br />Signaler un abus
    <br />La sauvegarde de mes recherches
    <br />la recherche automatique d'Annonces
  </p>
  <br /><br /><br />
  <h3>
    Fonctionnalités accessibles aux Utilisateurs enregistrés depuis le site
  </h3>
  <p>L'accès à l'espace "Mes favoris" :</p>
  <ul class="liste">
    <li>la sauvegarde d’articles</li>
    <li>la recherche automatique d’articles</li>
  </ul>
  <p>
    L'accès et la gestion du Compte Personnel : La gestion (actualisation,
    modification etc.), à tout moment, des informations personnelles renseignées
    lors de la création du Compte Personnel :
  </p>
  <ul class="liste">
    <li>
      Informations obligatoires : nom, prénom, email, mot de passe, numéro de
      téléphone portable
    </li>
    <li>
      Informations facultatives : civilité, âge, centre d'intérêt, secteur
      d'activité
    </li>
  </ul>
  <p>
    <br />La réception de notifications via la messagerie concernant les
    nouveaux résultats correspondant aux recherches sauvegardées.
  </p>
  <br /><br /><br />
  <div class="trait">
    <hr />
  </div>
  <h2>Vos droits</h2>
  <h3>Quels sont vos droits ?</h3>
  <p>
    <span>Droit d'accès :</span>
    il s’agit de votre droit d’obtenir la confirmation que vos données sont
    traitées ou non, et si oui, d’accéder à ces données.
    <br /><span>Droit de rectification :</span>
    il s’agit de votre droit d’obtenir, dans les meilleurs délais, que vos
    données inexactes soient rectifiées, et que vos données incomplètes soient
    complétées. Vous pouvez en outre, à tout moment, modifier les données
    personnelles de votre Compte Personnel, sauf votre adresse mail. Il vous
    suffit de vous rendre dans votre Compte Personnel et de cliquer sur l’onglet
    « Paramètres ».
    <br /><span>Droit de suppression/Effacement :</span>
    il s’agit de votre droit d’obtenir, dans les meilleurs délais, l’effacement
    de vos données, sous réserve de nos obligations légales de conservation.
    <br /><span>Droit de limitation :</span>
    il s’agit de votre droit d’obtenir la limitation du traitement lorsque vous
    vous y opposez, lorsque vous contestez l’exactitude de vos données, lorsque
    vous pensez que leur traitement est illicite, ou lorsque vous en avez besoin
    pour la constatation, l’exercice ou la défense de vos droits en justice.
    <br /><span>Droit d'opposition :</span>
    il s’agit de votre droit de vous opposer à tout moment au traitement de vos
    données, sauf en cas de motifs légitimes et impérieux. Vous pouvez également
    vous opposer au traitement fait à des fins de prospection.
    <br /><span>Droit à la portabilité :</span>
    il s’agit de votre droit de recevoir vos données dans un format structuré,
    couramment utilisé, lisible par machine et interopérable, et de les
    transmettre à un autre responsable du traitement sans que nous y fassions
    obstacle.
    <br /><span>Droit de ne pas faire l'objet d'une décision fondée sur un
      traitement automatisé :</span>
    vous avez le droit de ne pas faire l’objet d’une décision fondée
    exclusivement sur un traitement automatisé produisant des effets juridiques
    vous concernant ou vous affectant, sauf lorsque cette décision est
    nécessaire à la conclusion ou à l’exécution d’un contrat, ou est autorisée
    légalement.
    <br /><span>Réclamations :</span>
    vous avez le droit d’introduire une réclamation auprès d’une autorité de
    contrôle.
    <br /><span>Directives en cas de décès :</span>
    vous avez le droit de donner des directives pour le sort de vos données
    personnelles en cas de décès.
  </p>
  <h3>Comment exercer vos droits ?</h3>
  <p>
    Vous pouvez exercer vos droits d’accès, de rectification, de suppression et
    de portabilité via votre Compte dans l’onglet “Paramètres”.
    <br />Pour l’exercice de vos autres droits, vous devez vous adresser à notre
    support client via notre formulaire de contact.
    <br />Vous pouvez également exercer vos choix concernant notre utilisation
    des cookies.
  </p>
  <br /><br />
  <h3>Données à caractère personnel</h3>
  <p>
    Tout traitement de données personnelles dans le cadre des présentes est
    soumis aux dispositions de notre politique de confidentialité, qui fait
    partie intégrante des présentes CGU.
  </p>
  <br /><br />
  <h3>Droit d’introduire une réclamation auprès de la CNIL</h3>
  <p>
    L’article 79 du RGPD prévoit un « droit à un recours juridictionnel effectif
    contre un responsable du traitement».
    <br />La façon la plus simple de contacter la CNIL est de lui adresser une
    plainte en ligne via le formulaire présent à cette adresse :
    <a
      href="https://www.cnil.fr/fr/plaintes" target="_blank">https://www.cnil.fr/fr/plaintes</a>
  </p>
  <br /><br /><br />
  <div class="trait">
    <hr />
  </div>
  <h2>Consentement de notre politique de collecte de données</h2>
  <p>
    En cliquant sur « accepter » au bas de nos formulaires, vous consentez au
    stockage de vos données à des fins uniquement liées à ce site de e-commerce.
    Sinon votre inscription ou votre commande ne pourront pas être prises en
    compte.
  </p>
  <br /><br /><br />
  <div class="trait">
    <hr />
  </div>
  <h2>Services de livraison</h2>
  <h3>Livraison avec Mondial Relay :</h3>
  <p>
    Lorsque l'acheteur opte pour un envoi via le service de livraison Mondial
    Relay, l’acheteur est invité à choisir son point relais de livraison puis à
    renseigner ses informations d’identité avant de procéder au paiement du bien
    et des frais de livraison en ligne.
    <br /><span>Frais de Livraison :</span>
    <br />Le montant des frais de livraison varie selon la catégorie du bien
    envoyé (dimensions, poids).
    <br /><span>Envoi du colis :</span>

    <br />L’Acheteur est informé par email par notre société et par Mondial
    Relay de la disponibilité de son Colis dans le point relais de livraison
    choisi, ou en cas de changement, dans le point relais qui lui aura été
    indiqué par Mondial Relay.
    <br />Le Colis est disponible durant sept (7) jours calendaires, ce délai
    pouvant aller jusqu'à quatorze (14) jours calendaires, au-dit point relais
    de livraison et sera remis contre une pièce d’identité et contre une
    signature numérisée. Si le colis n’est pas récupéré, il sera renvoyé au
    point relais de départ et sera par la suite, disponible durant un délai de
    dix (10) jours calendaires. A l’issue de ce délai, le colis sera expédié au
    Service Expertise de Mondial Relay et sera disponible durant un délai de
    trente (30) jours. Passé ce délai, Mondial Relay pourra disposer librement
    du colis et les utilisateurs n’auront plus la possibilité de le récupérer.
    <br />Une fois la transaction validée et la bonne réception du bien
    confirmée par l’acheteur ou l’expiration du délai de 14 jours, notre société
    perçoit le montant de l’achat ainsi que les frais de livraison.
    <br />Le Service de Livraison Mondial Relay n’est pas disponible pour les
    biens dont le montant total (hors frais de livraison) excède 399 euros.
    <br />Les utilisateurs s’engagent à prendre connaissance des conditions
    générales de Mondial Relay en cliquant sur
    <a href="https://www.mondialrelay.fr/envoi-de-colis/conditions-generales-de-vente/" target="_blank">le
      lien suivant</a>
    <br />Pour contacter le Service Client de Mondial Relay, différents moyens
    sont mis à disposition de l’Utilisateur :
  </p>
  <ul class="liste">
    <li>
      Pour suivre votre Colis en temps réel :
      <a href="https://www.mondialrelay.fr/suivi-de-colis/" target="_blank">https://www.mondialrelay.fr/suivi-de-colis/</a>"
    </li>
    <li>
      Pour toute question, contactez l’adresse mail suivante :
      suividecolis@mondialrelay.fr (temps de réponse 2 jours ouvrés)
    </li>
    <li>
      Par téléphone au 09 69 32 23 32 du lundi au vendredi de 9h à 12h et de 14h
      à 17h30
    </li>
  </ul>
  <p>
    Dans le cadre du Service de Livraison, Mondial Relay engage sa
    responsabilité en cas de perte du Colis ou d’avarie constatée. En cas
    d’anomalie constatée quant à l’état du Colis lors de sa réception,
    l’Acheteur doit impérativement refuser le Colis.
    <br />Dans l’hypothèse d’un Colis perdu, une enquête interne au sein de
    Mondial Relay est ouverte au dixième jour suivant la dernière mise à jour du
    statut du Colis sur demande préalable de l’Utilisateur.
    <br />La durée moyenne d’une enquête est de vingt (20) jours.
    <br />Passé le délai de 14 jours à compter de la confirmation du paiement de
    l'Acheteur, aucun remboursement ne sera accordé à l'acheteur.
    <br />Dans l’hypothèse où le colis est déclaré à tort “réceptionné par
    l’acheteur”, il appartient à l’acheteur d’engager une procédure en
    contestation. Pour ce faire, l’Acheteur doit contacter le Service Client de
    Mondial Relay dans un délai de trois (3) jours maximum suivant la dernière
    mise à jour du statut du colis.
  </p>
  <h3>Livraison avec Colissimo/Lettre avec suivi (La Poste) :</h3>
  <p>
    Lorsque l’acheteur opte pour un envoi via le service de livraison
    Colissimo/Lettre avec suivi, celui-ci est invité à renseigner son adresse de
    livraison puis à renseigner ses informations d’identité avant de procéder au
    paiement du bien et des frais de livraison en ligne.
    <br /><span>Frais de Livraison :</span>
    <br />Le montant des frais de livraison varie selon la catégorie du bien
    envoyé (dimensions, poids).
    <br /><span>Envoi du colis :</span>
    <br />Le prix de vente du bien ne doit pas excéder 400 euros et les
    dimensions du colis doivent alternativement répondre aux critères suivants :
  </p>
  <ul class="liste">
    <li>La plus grande longueur du colis ne doit pas excéder 100 cm.</li>
    <li>
      Le développé du Colis (somme des largeur, longueur et hauteur) ne doit pas
      excéder 150 cm.
    </li>
  </ul>
  <p>
    Une fois le paiement réalisé par l’acheteur, un bordereau d’affranchissement
    Colissimo est généré par notre société.
    <br />Le vendeur s’engage à emballer convenablement le Colis, en respectant
    notamment les
    <a href="https://www.laposte.fr/bien-emballer-son-colis" target="_blank">règles et conseils
      de Colissimo</a>,
    <a href="https://www.laposte.fr/conditions-generales-de-vente" target="_blank">les
      Conditions Générales de Vente applicables aux prestations Courrier-Colis</a>
    et les
    <a href="https://www.laposte.fr/conditions-contractuelles" target="_blank">Conditions
      Spéciales de Vente</a>.
    <br />L’acheteur est informé par email par notre société et par La Poste de
    l’acheminement de son colis vers l’adresse de livraison renseignée.
    <br />Le colis sera déposé à l’adresse indiquée par l’acheteur, en boite aux
    lettres normalisée, sauf si les dimensions du colis ne le permettent pas ou
    si le colis nécessite une remise contre signature. Si le colis ne peut pas
    être déposé en boite aux lettres normalisée ou remis à l’acheteur, il sera
    distribué selon les modalités prévues dans les
    <a href="https://www.laposte.fr/conditions-generales-de-vente" target="_blank">Conditions
      Générales de Vente applicables aux prestations Courrier-Colis</a>
    ainsi que les
    <a href="https://www.laposte.fr/conditions-contractuelles" target="_blank">Conditions
      Spéciales de Vente</a>
    selon l'offre choisie, ou mis en instance dans un point de contact postal,
    pour un délai de 14 jours. A l’issue de ce délai, le colis sera réexpédié au
    vendeur.
    <br />Le service de livraison Colissimo n’est pas disponible pour les biens
    dont le montant total (hors frais de livraison) excède 400 euros. Les
    utilisateurs s’engagent à prendre connaissance des
    <a href="https://www.laposte.fr/conditions-generales-de-vente" target="_blank">
      Conditions Générales de Vente applicables aux prestations Courriers-Colis</a>
    ainsi que les
    <a href="https://www.laposte.fr/conditions-contractuelles" target="_blank">Conditions
      Spéciales de Vente</a>
    selon l’offre choisie.
    <br />Pour contacter le Service Client de Colissimo, différents moyens sont
    mis à disposition de l’utilisateur :
  </p>
  <ul class="liste">
    <li>
      Pour suivre votre Colis en temps réel :
      <a
        href="https://www.laposte.fr/outils/suivre-vos-envois" target="_blank">https://www.laposte.fr/outils/suivre-vos-envois</a>
    </li>
    <li>
      En cas de problème lors de la livraison :
      <a
        href="https://aide.laposte.fr/contact/colissimo/" target="_blank">https://aide.laposte.fr/contact/colissimo/</a>
    </li>
  </ul>
  <p>
    Passé le délai de 14 jours à compter de la confirmation du paiement de
    l'acheteur, aucun remboursement ne sera accordé à l'acheteur.
    <br />Dans l’hypothèse où le Colis est déclaré à tort “réceptionné par
    l’acheteur”, il appartient à l’acheteur d’engager une procédure en
    contestation. Pour ce faire, l’acheteur doit contacter le Service Client de
    Colissimo dans un délai de douze (12) mois à compter du lendemain du jour de
    prise en charge de l’envoi.
  </p>
  <br /><br /><br />
  <div class="trait">
    <hr />
  </div>
  <h2>Responsabilités et garanties</h2>
  <h3>Engagements du vendeur</h3>
  <p><br />Le vendeur s'engage notamment à ce que l'annonce ne contienne :</p>
  <ul class="liste">
    <li>
      aucun lien hypertexte redirigeant les utilisateurs notamment vers des
      sites internet exploités par toute autre société
    </li>
    <li>
      aucune information fausse, mensongère ou de nature à induire en erreur les
      utilisateurs
    </li>
    <li>
      aucun contenu portant atteinte aux droits de propriété intellectuelle de
      tiers
    </li>
  </ul>
  <p>
    <br />Le vendeur s'engage à ne proposer dans les annonces que des biens
    disponibles dont il dispose ou d’en faire mention en attente du
    réapprovisionnement. Le vendeur s’engage à proposer une description du bien
    conforme à ce qu’il est réellement (état, dimensions, poids, prix, etc.).
    <br />De manière générale, il est de la responsabilité du vendeur de
    vérifier son statut de particulier ou de professionnel, notamment au regard
    des articles L 121-1 et L 110-1 du Code de commerce selon lesquels "sont
    commerçants ceux qui exercent des actes de commerce et en font leur
    profession habituelle" et "La loi répute actes de commerce : tout achat de
    biens meubles pour les revendre, soit en nature, soit après les avoir
    travaillés et mis en oeuvre [...]".
    <br />Le vendeur s'engage à ce que son Compte Personnel ne contienne :
  </p>
  <ul class="liste">
    <li>aucune information obligatoire fausse et/ou mensongère</li>
    <li>aucune information portant atteinte aux droits d'un tiers</li>
  </ul>
  <p>
    Dans ce cadre, le titulaire déclare et reconnaît qu'il est seul responsable
    des informations renseignées lors de la création de son Compte Personnel.
  </p>

  <h3>
    Engagements spécifiques du vendeur et des acheteurs utilisant un service de
    paiement
  </h3>
  <p>
    Les acheteurs utilisant un service de paiement sur notre site déclarent :
  </p>
  <ul class="liste">
    <li>être des personnes physiques âgées de 18 ans ou plus</li>
    <li>
      assumer l’entière responsabilité des transactions réalisées sur le site,
      notamment l’engagement de l’acheteur à payer le bien acheté.
    </li>
  </ul>
  <br />
  <p>Par ailleurs, le vendeur et les acheteurs s’engagent à :</p>
  <ul class="liste">
    <li>Fournir des informations véridiques les concernant,</li>
    <li>
      Fournir des informations exactes et exhaustives concernant le bien faisant
      l’objet d’une offre de vente,
    </li>
    <li>
      Ne pas proposer à la vente des biens portant atteinte aux droits de
      propriété intellectuelle de tiers, notamment des propriétaires de la
      marque déposée, ou dont la vente est interdite par la réglementation
      française,
    </li>
    <li>
      Ne pas usurper l’identité ou le moyen de paiement d’un tiers pour réaliser
      des transactions via les services de notre site,
    </li>
    <li>
      Ne pas utiliser nos services de paiement en vue de réaliser des
      transactions illicites ou des actes frauduleux.
    </li>
  </ul>
  <br/>
  <p>
    En cas de suspicion d’une fraude quelconque par un acheteur, notre société
    se réserve le droit de suspendre immédiatement le compte de l’acheteur
    concerné ainsi que les transactions en cours.
  </p>
  <h3>
    Responsabilités du vendeur et des acheteurs dans le cadre de l'uilisation de
    nos services de paeiment
  </h3>
  <p>
    Il appartient au vendeur d’expédier le bien acheté à l’acheteur dans les
    plus brefs délais dès l’acceptation par le vendeur de l'offre d’achat. Le
    Vendeur est seul responsable de la livraison d’un bien et, en cas de litige,
    devra démontrer par tous moyens que le bien a été expédié (numéro de suivi
    du colis, reçu de paiement de l’envoi, messages échangés via la
    messagerie…).
    <br />La responsabilité de notre société ne pourra en aucun cas être engagée
    en cas d’absence de livraison du bien.
    <br />Le vendeur et l’acheteur sont seuls responsables d’organiser les
    conditions éventuelles de retour du bien avant le début de la transaction.
  </p>
  <h3>Limitation de responsabilité</h3>
  <p>Notre société décline toute responsabilité en cas de :</p>
  <ul class="liste">
    <li>
      interruptions, de pannes, de modifications et de dysfonctionnement du
      service Internet et des services de paiement ou du service de livraison,
      quel que soit le support de communication utilisé et ce quelles qu'en
      soient l'origine et la provenance,
    </li>
    <li>
      impossibilité momentanée d'accès au Site en raison de problèmes techniques
      et ce quelles qu'en soient l'origine et la provenance,
    </li>
    <li>
      utilisation anormale ou d'une exploitation illicite de nos services par
      tout utilisateur,
    </li>
    <li>
      Mauvaise exécution des transactions par les acheteurs dans le cadre de
      l’utilisation de nos services de paiement,
    </li>
    <li>
      attaque ou piratage informatique, privation, suppression ou interdiction,
      temporaire ou définitive, et pour quelque cause que ce soit, de l’accès au
      réseau internet.
    </li>
  </ul>
  <div class="trait">
    <hr />
  </div>
  <h2>Propriété intellectuelle</h2>
  <p>
    Tous les droits de propriété intellectuelle (tels que notamment droits
    d'auteur, droits voisins, droits des marques, droits des producteurs de
    bases de données) portant tant sur la structure que sur les contenus du site
    et notamment les images, sons, vidéos, photographies, logos, marques,
    éléments graphiques, textuels, visuels, outils, documents, données, etc.
    (ci-après désignés dans leur ensemble " Eléments ") sont réservés.
    <br />Ces Eléments sont la propriété de notre société. Ces Eléments sont mis
    à disposition des utilisateurs, à titre gracieux, pour la seule utilisation
    du service de notre site et des services de paiement, et dans le cadre d'une
    utilisation normale de ses fonctionnalités.
    <br />Toute utilisation non expressément autorisée des éléments du Site
    Internet entraîne une violation des droits d'auteur et constitue une
    contrefaçon. Elle peut aussi entraîner une violation des droits à l'image,
    droits des personnes ou de tous autres droits et réglementations en vigueur.
    Elle peut donc engager la responsabilité civile et/ou pénale de son auteur.
  </p>
  <div class="trait2">
  <hr />
  </div>
  <p>
    Il est interdit à tout utilisateur de copier, modifier, créer une œuvre
    dérivée, inverser la conception ou l'assemblage ou de toute autre manière
    tenter de trouver le code source, vendre, attribuer, sous licencier ou
    transférer de quelque manière que ce soit tout droit afférent aux Eléments.
    <br />Tout utilisateur s'engage notamment à ne pas :
  </p>
  <ul class="liste">
    <li>
      extraire, à des fins commerciales ou non, tout ou partie des informations
      ou des annonces présentes sur notre site ;
    </li>
    <li>
      reproduire sur tout autre support, à des fins commerciales ou non, tout ou
      partie des informations ou des annonces présentes sur notre Site Internet
      permettant de reconstituer tout ou partie des fichiers d'origine ;
    </li>
    <li>
      utiliser un robot, notamment d'exploration (spider), une application de
      recherche ou récupération de sites Internet ou tout autre moyen permettant
      de récupérer ou d'indexer tout ou partie du contenu de notre Site Internet
      ;
    </li>
    <li>
      copier les informations sur des supports de toute nature permettant de
      reconstituer tout ou partie des fichiers d'origine.
    </li>
  </ul>
  <p>
    Toute reproduction, représentation, publication, transmission, utilisation,
    modification ou extraction de tout ou partie des Eléments et ce de quelque
    manière que ce soit, faite sans l'autorisation préalable et écrite de notre
    site est illicite. Ces actes illicites engagent la responsabilité de ses
    auteurs et sont susceptibles d'entraîner des poursuites judiciaires à leur
    encontre et notamment pour contrefaçon.
  </p>

  <div class="trait2">
  <hr />
  </div>
  <p>
    Notre société est productrice et détentrice des bases de données. En
    conséquence, toute extraction et/ou réutilisation de la ou des bases de
    données au sens des articles L 342-1 et L 342-2 du code de la propriété
    intellectuelle est interdite.
  </p>
  <div class="trait2">
  <hr />
  </div>
  <p>
    Notre société se réserve la possibilité de saisir toutes voies de droit à
    l'encontre des personnes qui n'auraient pas respecté les interdictions
    contenues dans le présent article.
  </p>
  <div class="trait2">
  <hr />
  </div>
  <h3>Liens hypertextes à partir de notre site Internet</h3>
  <p>
    Notre site Internet peut contenir des liens hypertextes redirigeant vers des
    sites exploités par des tiers (par exemple le Service de Paiement Sécurisé).
    Notre société n'exerce aucun contrôle sur ces sites et décline toute
    responsabilité quant à l'accès, au contenu ou à l'utilisation de ces sites,
    ainsi qu'aux dommages pouvant résulter de la consultation des informations
    présentes sur ces sites. La décision d'activer ces liens relève de la pleine
    et entière responsabilité de l'utilisateur.
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Dispositions diverses</h2>
  <p>
    Notre société se réserve la possibilité de modifier, à tout moment, en tout
    ou partie des CGU. Les utilisateurs sont invités à consulter régulièrement
    les présentes CGU afin de prendre connaissance de changements éventuels
    effectués. L'utilisation de notre Site par les utilisateurs constitue
    l'acceptation par ces derniers des modifications apportées aux CGU.
    <br />Les présentes CGU sont soumises au droit français.
  </p>
</sectionCGU>
