<?php require '../views/header.phtml'; ?>

<sectionCookies>
  <h1>Politique de cookies</h1>
  <h2>Qu'est-ce qu'un cookie ?</h2>
  <p>
    Les cookies sont l'équivalent de simples fichiers texte de petite taille,
    stockés sur le disque dur de votre terminal (ordinateur, tablette, mobile)
    par le biais de votre logiciel de navigation à l'occasion de la consultation
    d'un service en ligne.
    <br />Les cookies ne stockent aucune donnée personnelle sensible ou
    directement identifiante mais donnent simplement une information sur votre
    navigation de façon à ce que votre terminal puisse être reconnu plus tard.
    <br />Ils permettent aux sites web de conserver des données utilisateur afin
    de faciliter la navigation et de permettre certaines fonctionnalités.
    <br />Ils ne sont donc pas exécutables. Ils ne sont ni des logiciels espions
    ni des virus.
    <br />Les cookies peuvent être utilisés pour mémoriser l'information sur
    l'utilisateur d'un site : pour une authentification, une session
    (maintenance d'état), et pour stocker une information spécifique sur
    l'utilisateur, comme les préférences d'un site web ou le contenu d'un panier
    d'achat électronique ou bien encore dans le but de montrer à l’utilisateur
    un contenu approprié dans le futur.
    <br />La plupart des navigateurs récents permettent aux utilisateurs de
    décider s'ils acceptent ou rejettent les cookies.
    <br />Toutefois, le rejet complet des cookies rend certains sites
    inutilisables. Par exemple, les paniers d'achat de magasins ou les sites qui
    exigent une connexion à l'aide d'identifiants (utilisateur et mot de passe).
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Les cookies fonctionnels que nous émettons nous permettent :</h2>
  <ul>
    <li>- de vous identifier lorsque vous vous connectez sur notre site</li>
    <li>
      - d'adapter la présentation de notre site aux préférences d'affichage de
      votre terminal (langue utilisée, résolution d'affichage, système
      d'exploitation utilisé, etc.), selon les matériels et les logiciels de
      visualisation ou de lecture que votre terminal comporte
    </li>
    <li>
      - de faciliter vos recherches en conservant vos recherches automatiques
    </li>
    <li>
      - d'améliorer votre expérience utilisateur en pré-remplissant certains
      champs de nos for-mulaires
    </li>
  </ul>
  <p>Ces cookies ont une durée de conservation de 12 mois.</p>
  <div class="trait">
    <hr />
  </div>
  <h2>Vos choix personnels</h2>
  <h3>Politique de cookies</h3>
  <p>
    Vous pouvez à tout moment configurer votre navigateur de manière à ce que
    des cookies soient enregistrés dans votre terminal (opt-in) ou, au
    contraire, qu'ils soient rejetés (opt-out). Certains navigateurs vous
    permettent de définir des règles pour gérer les cookies site par site.
    <br />Pour la gestion des cookies, la configuration de chaque navigateur est
    différente. Elle est décrite dans le menu d'aide de votre navigateur, qui
    vous permettra de savoir de quelle manière modifier vos souhaits :
  </p>
  <ul>
    <li>
      <a
        href="https://assistance.orange.fr/ordinateurs-peripheriques/installer-et-utiliser/la-recherche-et-navigation-sur-le-web-cookies/un-navigateur/edge/microsoft-edge-gerer-les-cookies_155843-353064" target="_blank">Edge</a>
    </li>
    <li>
      <a
        href="https://support.microsoft.com/fr-fr/help/17442/windows-internet-explorer-delete-manage-cookies#:~:text=Dans%20Internet%20Explorer%2C%20s%C3%A9lectionnez%20le%20bouton%20Outils%20%2C%20puis%20Options%20Internet,internes%20et%20les%20cookies%20tiers." target="_blank">Internet
        Explorer</a>
    </li>
    <li>
      <a
        href="https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=fr" target="_blank">Chrome</a>
    </li>
    <li>
      <a
        href="https://support.mozilla.org/fr/kb/protection-renforcee-contre-pistage-firefox-ordinateur" target="_blank">Firefox</a>
    </li>
    <li>
      <a
        href="https://assistance.orange.fr/ordinateurs-peripheriques/installer-et-utiliser/la-recherche-et-navigation-sur-le-web-cookies/un-navigateur/opera/opera-gerer-les-cookies_291992-832614" target="_blank">Opera</a>
    </li>
    <li>
      <a
        href="https://support.apple.com/fr-fr/guide/safari/sfri11471/mac" target="_blank">Safari</a>
    </li>
  </ul>
  <p>
    Nous vous invitons également à nous contacter pour toute question ou requête
    relative aux cookies déposés sur notre site, en suivant
    <a href="#" target="_blank">ce lien.</a>
  </p>
  <br />
  <p>
    Cependant, les cookies opérationnels vous permettent de bénéficier de
    certaines fonctionnalités essentielles de notre site. Si vous bloquez ou
    refusez les cookies opérationnels dans les paramètres de votre navigateur,
    certaines fonctionnalités peuvent ne pas fonctionner. Par exemple, vous ne
    serez pas en mesure de créer un compte ou de vous y connecter, d’ajouter des
    articles à votre panier, de passer votre commande, toutes fonctionnalités
    qui nécessitent que vous soyez connecté à votre compte. Il se peut que vous
    soyez obligé d’ajuster vos préférences manuellement à chaque fois que vous
    voudrez utiliser nos services.
  </p>
    </sectionCookies>
