<?php require '../views/header2.phtml'; ?>

<div>
    <div class="accueil">
        <br />
        <div class="bonjour">Bonjour <?= htmlspecialchars($username['username']) ?>
        </div>
        <br />
    </div>
</div>


<div class="flex">
<div>
<a href="../controllers/agenda.php"><button class="button">Vous souhaitez prendre un rendez-vous ?</button></a>
</div>
<div>
    <a href="../controllers/home.php"><button class="button2">Retour à l'accueil</button></a>
</div>
</div>