<footer id="footer">
    <div class="coordonnees">
      <div class="mail">contact@sata-system.com</div>
      <div class="adresse">SARL SATA &nbsp;24 rue de Lorraine 54300 LUNEVILLE</div>
    </div>

    <div class="responsabilites">
      <a href="../controllers/CGU.php" target="_blank">Conditions Générales d'Utilisation</a>
      <a href="../controllers/RGPD.php" target="_blank">Vos informations personnelles</a>
      <a href="../controllers/cookies.php" target="_blank">Cookies</a>
    </div>
</footer> 

 
<script type="text/javascript" src="../resources/js/script.js"></script>
  </body>
</html>