<footer id="footer">
			<div class=ligne1>
				<p>A propos</p>
        <p>Informations légales</p>
        <p>Pour nous contacter</p>
			</div>

			<div class="ligne2">
        <div class="copyright">
            <i class="far fa-copyright"></i>
            <p>&nbsp; Leboncoin de la Préhistoire</p>
        </div>
        <div class="facebook">
              <p class="retrouvez">Retrouvez-nous sur&emsp; </p>
              <a href="https://fr-fr.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></a>
        </div>
			</div>
</footer> 

 
  </body>
</html>