<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="keywords" content="Sat@,Sata Contact,sata-system,sata-alarme,alarme">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Snowburst+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="../resources/css/style.css" />
  <link rel="stylesheet" href="../resources/css/header.css" />
  <link rel="stylesheet" href="../resources/css/footer.css" />
  <link rel="stylesheet" href="../resources/css/dashboardUser.css" />
  <link rel="stylesheet" href="../resources/css/form.css" />
  <link rel="stylesheet" href="../resources/css/sidePanel.css" />
  <link rel="stylesheet" href="../resources/css/CGU.css" />
  <link rel="stylesheet" href="../resources/css/cookies.css" />
  <link rel="stylesheet" href="../resources/css/RGPD.css" />
  <title>SATA SARL Lunéville</title>

 

  <!--
    <link rel="icon" href="wpimages/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="wpimages/favicon.ico" type="image/x-icon">
-->


</head>




<body>

  <header class="header">

 
    <div><a href="../controllers/home.php"><img src="../resources/img/logo4.png" class="logo" alt="logo" title="logo"></a></div>
    <input class="menu-btn" type="checkbox" id="menu-btn" />
    <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>

  
    <ul class="menu">
    <?php
    if (!isset($_SESSION['identification'])) {
    ?>

      <li>
      <button onclick="openNav()" class="identification">Inscription</button>
      </li>

      <li>
      <button onclick="openNav2()" class="identification">Connexion</button>
      </li>
    <?php
    }
    ?>
    </ul>

  </header>


