<?php require '../views/header.phtml'; ?>

  <body>
    <section>



    <div class="wrap">
      <div><img src="../resources/img/devanture.jpg" class="devanture" alt="devanture de la boutique SATA à Lunéville" title="devanture"></div>
     
      <div><iframe class="video" width="300" height="200" src="https://www.youtube.com/embed/7uWLTCjSozc?list=PLdVIHOet5WuPUl-X8UeEBApJs64dywFPO" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>


      <div><a href="../controllers/page2.php"><img src="../resources/img/silhouette.png" class="silhouette" alt="silhouette entrant" title="silhouette"></a></div>
     

      <div><img src='../resources/img/studiob.jpg' class="multimedia" alt="multimédia" title="multimédia"></div>

    </div>
    

    <div class="description">
        <p class="h3">RISCO Group</p>
        <p>Agility 3</p>
        <p>Un système de sécurité sans fil pour protéger votre famille et vos biens.</p>
    </div>


    </section>



<?php require '../views/footer.phtml'; ?>