<?php require '../views/header.phtml'; ?>

  <body>
    <section>



    <div class="wrap">
      <div><img src="../resources/img/devantureb.jpg" class="devanture" alt="devanture de la boutique SATA à Lunéville" title="devanture"></div>
     
      <div><iframe class="video" src="https://www.youtube.com/embed/7uWLTCjSozc?list=PLdVIHOet5WuPUl-X8UeEBApJs64dywFPO" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

      <div><a href="../controllers/page2.php"><img src="../resources/img/silhouette.png" class="silhouette" alt="cliquer sur la silhouette pour entrer" title="Entrer"></a></div>
     
    </div>
    

    <div class="description">
        <p class="h3">RISCO Group</p>
        <br/>
        <p class="agility">Agility 3</p>
        <br/>
        <p class="texte">Un système de sécurité sans fil pour protéger votre famille et vos biens.</p>
    </div>


    </section>



<?php require '../views/footer.phtml'; ?>