<link rel="stylesheet" href="../resources/css/header3.css" />
<link rel="stylesheet" href="../resources/css/page2.css" />

  <body>


<div class="bg"></div>
<div class="bg2"></div>

<div class="container">
  <div id="left">
    <h1>Agence SATA Lunéville</h1>
    <p>Vous souhaitez prendre un rendez-vous ?<br/>Connaître les produits en stock ?<br/>Une question particulière ? </p>
  </div>
  <div id="right">
    <ul>
      <li> 
        <img src="../resources/img/logo4.png" class="logo1" alt="logo" title="logo">
        <span>
          
          <a href="../controllers/agenda.php" target="_blank" class="text"><strong>Prendre un rendez-vous</strong></a>

        </span>

        
      </li>
      <li> 
      <img src="../resources/img/logo4.png" class="logo1" alt="logo" title="logo">
        <span>
          <strong>Produits en stock</strong>
        </span>
      </li>
      <li> 
        <img src="../resources/img/logo4.png" class="logo1" alt="logo" title="logo">
        <span>
          <strong>Une question ?</strong>
        </span>
      </li>
    </ul>
  </div>
</div>



  </body>






