<?php require '../views/header.phtml'; ?>

  <body>
    <section id="sect">
  <div class="container">
    <input type="radio" name="slider" id="item-1" checked>
    <input type="radio" name="slider" id="item-2">
    <input type="radio" name="slider" id="item-3">
    <input type="radio" name="slider" id="item-4">
    <input type="radio" name="slider" id="item-5">


    
  <div class="cards">
    <label class="card" for="item-1" id="photo-1">
      <img src="../resources/img/interieur.jpg" class="photo" alt="intérieur">
    </label>
    <label class="card" for="item-2" id="photo-2">
      <img src="../resources/img/20170511_181345.jpg" class="photo" alt="">
    </label>
    <label class="card" for="item-3" id="photo-3">
      <img src="../resources/img/20170511_181403.jpg" class="photo" alt="">
    </label>






    <label class="card" for="item-4" id="photo-4">
      <img src="../resources/img/20170511_181430.jpg" class="photo" alt="">
    </label>
    <label class="card" for="item-5" id="photo-5">
      <img src="../resources/img/Show-room.jpg" class="photo" alt="show-romm alarmes">
    </label>


  </div>

</div> 
   


</section>



<?php require '../views/footer.phtml'; ?>

