<?php require '../views/header.phtml'; ?>

<sectionRGPD>
  <h1>Règlement Général sur la Protection des Données</h1>
  <div class="trait">
    <hr />
  </div>
  <h2>Type de données collectées</h2>
  <h3>Les données que vous renseignez</h3>
  <p>
    CREATION DE COMPTE
    <br />Lorsque vous créez votre Compte Personnel, vous devez nous communiquer
    vos :
    <br />nom,
    <br />prénom,
    <br />adresse email
    <br /><br />
    Vous pouvez également choisir de nous communiquer les informations suivantes
    :
    <br />Civilité
    <br />Numéro de Téléphone
    <br />Date de naissance
    <br />Catégorie socioprofessionnelle
    <br />Centres d’intérêts
    <br />
  </p>
  <br />
  <p>
    COMMANDE
    <br />Lorsque vous effectuez une commande, vous devez nous communiquer vos :
    <br />nom,
    <br />prénom,
    <br />adresse email,
    <br />adresse postale,
    <br />n° de téléphone portable,
    <br />éventuellement le n° de téléphone fixe,
    <br />
  </p>
  <h3>
    Les données que nous collectons automatiquement par votre utilisation de nos
    services
  </h3>
  <p>
    Nous enregistrons des données d’utilisation lorsque vous accédez à nos
    services, notamment quand vous effectuez une recherche, quand vous passez
    une commande, ou quand vous nous contactez par email.
    <br />Nous collectons des informations de navigation : le cheminement URL
    complet vers et via notre site Internet, y compris les date et heure, les
    numéros de "cookies", les produits et/ou contenus que vous avez consultés ou
    recherchés, les temps de réponse d'une page, les erreurs de téléchargement,
    les informations concernant les interactions sur une page (« scrolling
    »(défilement sur une page), clics, mouvements de souris).
    <br />Nous utilisons des identifiants de connexion (notamment des
    identifiants concernant vos appareils mobiles) et des cookies ainsi que
    votre adresse IP (qui relie votre ordinateur ou tout autre appareil à
    Internet) pour vous identifier et pour enregistrer votre activité.
    <br />Nous sommes également susceptibles de collecter des données techniques
    sur votre connexion internet, votre navigateur et vos appareils.
  </p>
  <br />
  <h3>Informations auxquelles vous avez accès</h3>
  <p>
    le statut de vos commandes récentes.
    <br />votre historique de commande complet.
    <br />vos informations personnelles (notamment vos nom, adresse e-mail,
    adresse postale et mot de passe).
    <br />les recommandations et les produits que vous avez récemment consultés
    à partir desquels ont été établies les recommandations.
    <br />les paramètres relatifs à vos contenus, appareils, services et tout
    autre paramètre en lien avec ceux-ci.
    <br />les contenus récemment consultés.
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Utilisation de vos données</h2>
  <p>
    Nous utilisons vos données pour les finalités suivantes :
    <br />COMMANDE : Nous utilisons vos informations personnelles aux fins de
    l'enregistrement et du traitement des commandes et de communication avec
    vous en relation avec vos commandes et les produits.
    <br />RECOMMANDATIONS : Nous utilisons vos informations personnelles afin de
    vous recommander des produits.
    <br />Prévention de la fraude : Nous traitons vos informations personnelles
    afin de prévenir et détecter les fraudes.
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Destinataires des données</h2>
  <h3 class="ligne">Identité et coordonnées de l'entreprise :</h3>
  <p class="ligne">(à renseigner ici)</p>
  <p>
    Le responsable du traitement des données (pour toutes questions concernant
    vos données personnelles) : (à renseigner ici)
  </p>
  <p>
    Afin de respecter nos obligations légales, vos données personnelles peuvent
    être transmises aux autorités administratives et judiciaires autorisées,
    uniquement sur réquisition judiciaire.
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Durée de conservation des données</h2>
  <p>
    La durée de conservation de vos données personnelles varie en fonction de la
    finalité de leurs collectes :
    <br />Les données de Compte (identité, coordonnées électroniques, historique
    d’utilisation des services) sont conservées 3 ans à compter de la fin de la
    relation commerciale ;
    <br />Les données relatives à la gestion de votre Compte sont conservées
    pour une durée de 5 ans à compter de leur suppression et ce, exclusivement à
    des fins de preuve ;
    <br />Les documents et pièces comptables sont conservés 10 ans, à titre de
    preuve comptable ;
    <br />Les emails collectés dans le cadre du formulaire de contact sont
    conservées 12 mois à compter de leur collecte;
    <br />Les données susceptibles de faire l’objet d’une réquisition judiciaire
    (données de connexion, identité, coordonnées de contact) sont conservées 12
    mois à compter de leur collecte ;
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Vos droits</h2>
  <h3>Quels sont vos droits ?</h3>
  <p>
    <span>Droit d'accès :</span>
    il s’agit de votre droit d’obtenir la confirmation que vos données sont
    traitées ou non, et si oui, d’accéder à ces données.
    <br /><span>Droit de rectification :</span>
    il s’agit de votre droit d’obtenir, dans les meilleurs délais, que vos
    données inexactes soient rectifiées, et que vos données incomplètes soient
    complétées. Vous pouvez en outre, à tout moment, modifier les données
    personnelles de votre Compte Personnel, sauf votre adresse mail. Il vous
    suffit de vous rendre dans votre Compte Personnel et de cliquer sur l’onglet
    « Paramètres ».
    <br /><span>Droit de suppression/Effacement :</span>
    il s’agit de votre droit d’obtenir, dans les meilleurs délais, l’effacement
    de vos données, sous réserve de nos obligations légales de conservation.
    <br /><span>Droit de limitation :</span>
    il s’agit de votre droit d’obtenir la limitation du traitement lorsque vous
    vous y opposez, lorsque vous contestez l’exactitude de vos données, lorsque
    vous pensez que leur traitement est illicite, ou lorsque vous en avez besoin
    pour la constatation, l’exercice ou la défense de vos droits en justice.
    <br /><span>Droit d'opposition :</span>
    il s’agit de votre droit de vous opposer à tout moment au traitement de vos
    données, sauf en cas de motifs légitimes et impérieux de LBC France. Vous
    pouvez également vous opposer au traitement fait à des fins de prospection.
    <br /><span>Droit à la portabilité :</span>
    il s’agit de votre droit de recevoir vos données dans un format structuré,
    couramment utilisé, lisible par machine et interopérable, et de les
    transmettre à un autre responsable du traitement sans que nous y fassions
    obstacle.
    <br /><span>Droit de ne pas faire l'objet d'une décision fondée sur un
      traitement automatisé :</span>
    vous avez le droit de ne pas faire l’objet d’une décision fondée
    exclusivement sur un traitement automatisé produisant des effets juridiques
    vous concernant ou vous affectant, sauf lorsque cette décision est
    nécessaire à la conclusion ou à l’exécution d’un contrat, ou est autorisée
    légalement.
    <br /><span>Réclamations :</span>
    vous avez le droit d’introduire une réclamation auprès d’une autorité de
    contrôle.
    <br /><span>Directives en cas de décès :</span>
    vous avez le droit de donner des directives pour le sort de vos données
    personnelles en cas de décès.
  </p>
  <h3>Comment exercer vos droits ?</h3>
  <p>
    Vous pouvez exercer vos droits d’accès, de rectification, de suppression et
    de portabilité via votre Compte dans l’onglet “Paramètres”.
    <br />Pour l’exercice de vos autres droits, vous devez vous adresser à notre
    support client via notre formulaire de contact.
    <br />Vous pouvez également exercer vos choix concernant notre utilisation
    des cookies en cliquant ici.
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Droit d’introduire une réclamation auprès de la CNIL</h2>
  <p>
    L’article 79 du RGPD prévoit un « droit à un recours juridictionnel effectif
    contre un responsable du traitement».
    <br />La façon la plus simple de contacter la CNIL est de lui adresser une
    plainte en ligne via le formulaire présent à cette adresse :
    <a
      href="https://www.cnil.fr/fr/plaintes" target="_blank">https://www.cnil.fr/fr/plaintes</a>
  </p>
  <div class="trait">
    <hr />
  </div>
  <h2>Consentement de notre politique de collecte de données</h2>
  <p>
    En cliquant sur « accepter » au bas de nos forumulaires, vous consentez au
    stockage de vos données à des fins uniquement liées à ce site de e-commerce.
    Sinon votre inscription ou votre commande ne pourront pas être prises en
    compte.
  </p>
  <div class="trait">
    <hr />
  </div>
</sectionRGPD>
