<?php require '../views/header.phtml'; ?>


  <main class="form-style-10">
    <h1>Inscription</h1>
    <form action="../controllers/signUp.php" method="POST">
     
      <div class="section"><span>1</span>Email</div>
      <div class="inner-wrap">
        <label>Votre Email<input type="email" name="email" value="<?php echo isset($_GET['email'])?$_GET['email']:'' ?>" required /></label>
      </div>

      <div class="section"><span>2</span>Pseudo</div>
      <div class="inner-wrap">
        <label>Votre Pseudo <input type="text" name="pseudo" value="<?php echo isset($_GET['pseudo'])?$_GET['pseudo']:'' ?>" required></input></label>
      </div>

      <div class="section"><span>3</span>Mot de passe</div>
      <?php if (isset($_GET['error']) && $_GET['error'] == 'passwordmatch'){ ?>
        <script>alert ('Les mots de passe ne correspondent pas');</script>
      <?php } ?>
      <div class="inner-wrap">
        <label>Votre mot de passe <input type="password" name="password" required /></label>
        <label>Confirmez votre mot de passe <input type="password" name="passwordconfirm" required /></label>
      </div>

      <span class="privacy-policy">
        <input type="checkbox" name="field7" class="field"/>&emsp;J'accepte les conditions générales d'Utilisation et de Vente
        </span>
      <div class="button-section10">
        <input type="submit" name="signUp" />
      </div>
    </form>
      </main>


<?php require '../views/footer.phtml'; ?>