<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="keywords" content="Sat@,Sata Contact,sata-system,sata-alarme,alarme">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Snowburst+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">


  <link rel="stylesheet" href="../resources/css/signInerror.css" />
  <title>SATA SARL Lunéville</title>
</head>





  <body>

  <formul2 class="form-style-1">
    <h1>Connexion</h1>
      <form action="../controllers/signIn.php" method="POST">
          <div class="section"><span>1</span>Pseudo</div>
          <div class="inner-wrap">
              <label>Votre Pseudo<input type="pseudo" name="username" required></label>
          </div>
          <div class="section"><span>2</span>Mot de passe</div>
              <div class="inner-wrap">
              <label>Votre mot de passe<input type="password" name="password" required/></label>
          </div>
          <div class="button-section">
          <input type="submit" name="SignIn" />
          </div>
      </form>
  </formul2>
</body>
</html>